### ISSUE TITLE
Header Modification suggestion for use with reverse proxy (i.e. nginx)

### ISSUE THREAD

**Issue by ogklavas** [likerRr/sse-express#22]
I would suggest that the following header is added to  res.writeHead in the sseMiddleware function:

'X-Accel-Buffering':'no'

This allows SSE to keep functioning if the app server is a reverse proxy with SSL

**Comment by likerRr** [comment]
Hi, thank you for suggestion. Can you provide more info about this header? Like a spec or a good article

**Comment by ogklavas** [comment]
Hi,
Have a look at the accepted reply to this post: https://serverfault.com/questions/801628/for-server-sent-events-sse-what-nginx-proxy-configuration-is-appropriate

**Comment by likerRr** [comment]
Thanks a lot, gimme time to review this

**Comment by davewat** [comment]
#26 
Just created a pull request for this fix.

**Comment by likerRr** [comment]
@davewat well done, thx. Published as `sse-express@next`
